### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [ankeshdave/CalendarSyncplus#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by ankeshdave** [comment]
Hi karan,
Thanks for reminding, I have added the same license as this projects holds on its [codeplex site](https://calendarsyncplus.codeplex.com/license).
